### ISSUE TITLE
Angular pack: no template highlighting

### ISSUE THREAD

**Issue by osenvosem** [AstroNvim/astrocommunity#498]
Installed the Angular pack but angular templates is still highlighted as simple html files.

<img width="455" alt="Screenshot 2023-08-04 at 19 00 04" src="https://github.com/AstroNvim/astrocommunity/assets/6762673/e93245ff-62a0-450b-aaec-05fd658f3bc9">

Has anyone it working?

**Comment by kmiasko** [comment]
It's probably mismatch of ABI between angularjs treesitter and newer neovim.

https://github.com/nvim-treesitter/nvim-treesitter-angular/issues/2

You need to build tree sitter plugin manually.

**Comment by osenvosem** [comment]
> It's probably mismatch of ABI between angularjs treesitter and newer neovim.

I think in this case I would see the corresponding error in `checkhealth`. There is no error.

If it is necessary to build something manually, why do I need this pack?) In this case the fork should be part of the pack.

**Comment by Uzaaft** [comment]
> > It's probably mismatch of ABI between angularjs treesitter and newer neovim.
> 
> I think in this case I would see the corresponding error in `checkhealth`. There is no error.
> 
> If it is necessary to build something manually, why do I need this pack?) In this case the fork should be part of the pack.

Feel free to create a PR then, if you think this fork should be part of the pack.

**Comment by Uzaaft** [comment]
Do any of you guys use https://github.com/joeveiga/ng.nvim ? Experiences?

**Comment by Uzaaft** [comment]
> > It's probably mismatch of ABI between angularjs treesitter and newer neovim.
> 
> I think in this case I would see the corresponding error in `checkhealth`. There is no error.
> 
> If it is necessary to build something manually, why do I need this pack?) In this case the fork should be part of the pack.

Re this:
The packs tries to solve the initial setup for new users by providing a starting point and an easy to setup solution. Alas, we can't compensate for the bad state of angular TS stuff.

**Comment by Uzaaft** [comment]
Going ahead and closing this due to inactivity.

**Comment by osenvosem** [comment]
> Re this:
> The packs tries to solve the initial setup for new users by providing a starting point and an easy to setup solution. Alas, we can't compensate for the bad state of angular TS stuff.

There is a working fork you could use in this pack https://github.com/nvim-treesitter/nvim-treesitter-angular/issues/3

> Going ahead and closing this due to inactivity.

While the problem isn't solved.

**Comment by Uzaaft** [comment]
> > Re this:
> > The packs tries to solve the initial setup for new users by providing a starting point and an easy to setup solution. Alas, we can't compensate for the bad state of angular TS stuff.
> 
> There is a working fork you could use in this pack [nvim-treesitter/nvim-treesitter-angular#3](https://github.com/nvim-treesitter/nvim-treesitter-angular/issues/3)
> 
> > Going ahead and closing this due to inactivity.
> 
> While the problem isn't solved.

Due to inactivtiy.
An I'm not sure which fix you're refering to by linking that issue...A link to the comment fixing the issue would be more helpfull.

**Comment by osenvosem** [comment]
> An I'm not sure which fix you're refering to by linking that issue...A link to the comment fixing the issue would be more helpfull.

`use({ "elgiano/nvim-treesitter-angular", branch = "topic/jsx-fix" })`

**Comment by Uzaaft** [comment]
Please check the code in the pack. :)

**Comment by osenvosem** [comment]
> Please check the code in the pack. :)

Yep, but it still doesn't work while people in the issue stated that it does for them. Don't know why... 🫤

**Comment by Uzaaft** [comment]
> > Please check the code in the pack. :)
> 
> Yep, but it still doesn't work while people in the issue stated that it does for them. Don't know why... 🫤

And people are also saying that it DIDN't fix the issue, so 🤷🏾‍♂️

**Comment by osenvosem** [comment]
> > > Please check the code in the pack. :)
> > 
> > 
> > Yep, but it still doesn't work while people in the issue stated that it does for them. Don't know why... 🫤
> 
> And people are also saying that it DIDN't fix the issue, so 🤷🏾‍♂️

It didn't fixed the issue with **inline** templates.

Here I found the fork with regenerated parser, it should fix the issue with incorrect ABI version https://github.com/ShooTeX/tree-sitter-angular/tree/main

<img width="944" alt="Screenshot 2023-11-05 at 16 38 29" src="https://github.com/AstroNvim/astrocommunity/assets/6762673/2f77bf48-acff-4045-a70f-b52b1bb3d545">

**Comment by Uzaaft** [comment]
We'll have to check to see if there are any other issues with that fork. I'll re-open the issue

**Comment by osenvosem** [comment]
> We'll have to check to see if there are any other issues with that fork. I'll re-open the issue

Thank you.

**Comment by osenvosem** [comment]
@Uzaaft cloned repos and applied fixes to each. Could you please try if it's working?

https://github.com/osenvosem/tree-sitter-angular
https://github.com/osenvosem/nvim-treesitter-angular

**Comment by Theaninova** [comment]
Doesn't seem to fix everything for me, the Angular thing says it's working but TypeScript is still broken.

```
The following errors have been detected: ~
- ERROR typescript(injections): ...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 7470 for language typescript
  typescript(injections) is concatenated from the following files:
  |    [OK]:"/nix/store/7m3zm75rdg8bfk17wvjysrd5s361a5h7-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/ecma/injections.scm"
  |    [OK]:"/nix/store/7m3zm75rdg8bfk17wvjysrd5s361a5h7-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/ecma/injections.scm"
  | [ERROR]:"/nix/store/7m3zm75rdg8bfk17wvjysrd5s361a5h7-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/jsx/injections.scm", failed to load: ...ed-0.9.4/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 26 for language typescript
  |    [OK]:"/nix/store/7m3zm75rdg8bfk17wvjysrd5s361a5h7-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/javascript/injections.scm"
  |    [OK]:"/nix/store/7m3zm75rdg8bfk17wvjysrd5s361a5h7-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/queries/typescript/injections.scm"
```

**Comment by osenvosem** [comment]
The Angular parser has been merged into the nvim-treesitter.

https://github.com/nvim-treesitter/nvim-treesitter/commit/1e74c34b668d0bbdd14492fc220974e4fc38dc6b
