### ISSUE TITLE
eslint or prettierd error

### ISSUE THREAD

**Issue by taotao7** [AstroNvim/astrocommunity#966]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

macos 14.4.1

### Terminal/GUI

iterm2

### Describe the bug

The first file source code file can be automatically formatted, but the second open file will be formatted failed, not sure when prettier or eslint problem, delete the eslint configuration file can be, as long as the project under the existence of eslint configuration rules will appear this problem!

### Steps to Reproduce

1. front or node project 
2. have eslint config 
module.exports = {
  root: true,
  env: { browser: true, es2020: true },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react-hooks/recommended',
  ],
  ignorePatterns: ['dist', '.eslintrc.cjs'],
  parser: '@typescript-eslint/parser',
  plugins: ['react-refresh'],
  rules: {
    'react-refresh/only-export-components': [
      'warn',
      { allowConstantExport: true },
    ],
    '@typescript-eslint/no-explicit-any': ['off'],
    'react-hooks/rules-of-hooks': ['off'],
    'react-hooks/exhaustive-deps': 'off',
  },
}
3. open one ts or js file
4. save format
5. open two ts or js file
6. format error

### Expected behavior

save format can be normal

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/24582204/5760848a-64e4-4b10-ad61-a6264b955212)

### Additional Context

The file is not important, as long as it is the second open file, it will not be formatted

**Comment by Uzaaft** [comment]
Try and re-install the LSP's.

**Comment by fynnfluegge** [comment]
Similar issue here, have to uninstall `astrocommunity.pack.typescript` to fix it 🥹

**Comment by gabrielscaranello** [comment]
Same problem here. I tried using previous versions of astrocommunity, but it still didn't work.

**Comment by taotao7** [comment]
> Try and re-install the LSP's.  

not work ，may be lsp server error

**Comment by taotao7** [comment]
I guess there should be something wrong with the pretterd version installed by Mason.

**Comment by taotao7** [comment]
I guess there should be something wrong with the pretterd version installed by Mason.

**Comment by taotao7** [comment]
> Similar issue here recently, had to uninstall `astrocommunity.pack.typescript` to fix it 🥹

i know ,but if I were to remove the typescript pack, wouldn't I not support JS TS?🧐

**Comment by taotao7** [comment]
Brothers, please return to 8.3.0 for the time being. I tested this version and it works fine.

user.lua
  {

    "AstroNvim/astrocommunity",
    version = "8.3.0",
  },

**Comment by taotao7** [comment]
@fynnfluegge 
@gabrielscaranello

**Comment by MrMic** [comment]
Same issue here. It seems to have something to do with prettier.
I saw some updates about this recently.

![Capture d’écran du 2024-05-16 09-57-45](https://github.com/AstroNvim/astrocommunity/assets/5823264/59dd118d-17b8-4e40-92d0-a7b36274612d)

**Comment by taotao7** [comment]
> Same issue here. It seems to have something to do with prettier.
> 
> I saw some updates about this recently.
> 
> 
> 
> ![Capture d’écran du 2024-05-16 09-57-45](https://github.com/AstroNvim/astrocommunity/assets/5823264/59dd118d-17b8-4e40-92d0-a7b36274612d)
> 
> 
> 
> 
> 
> **BTW**:  Switching to 8.3.0 does not fix the issue. I still have this, 
> 
> with NextJS projects...

try to edit eslint config

{
  "extends": "next"
}

**Comment by MrMic** [comment]
> > Same issue here. It seems to have something to do with prettier.
> > I saw some updates about this recently.
> > ![Capture d’écran du 2024-05-16 09-57-45](https://private-user-images.githubusercontent.com/5823264/331107381-59dd118d-17b8-4e40-92d0-a7b36274612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjQ4MjUsIm5iZiI6MTcxNTg2NDUyNSwicGF0aCI6Ii81ODIzMjY0LzMzMTEwNzM4MS01OWRkMTE4ZC0xN2I4LTRlNDAtOTJkMC1hN2IzNjI3NDYxMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTMwMjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDMxMzQzZWRjZTI3NWRmNjgwNWM2NWVmYzFjNzI3MTRmOGRhNTAwM2YzMGNmZTRhMDUwZDgxOWRmYjg3OWFlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pfKECYCWV4hAvz2XtsfdZgSrbr0NfDBzIbkAqYnBUDk)
> > **BTW**:  Switching to 8.3.0 does not fix the issue. I still have this,
> > with NextJS projects...
> 
> try to edit eslint config
> 
> { "extends": "next" }

We are all senior Devs here, so I have done this and much more to 
solve this issue...

**Comment by taotao7** [comment]
> > > Same issue here. It seems to have something to do with prettier.
> 
> > > I saw some updates about this recently.
> 
> > > ![Capture d’écran du 2024-05-16 09-57-45](https://private-user-images.githubusercontent.com/5823264/331107381-59dd118d-17b8-4e40-92d0-a7b36274612d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NjQ4MjUsIm5iZiI6MTcxNTg2NDUyNSwicGF0aCI6Ii81ODIzMjY0LzMzMTEwNzM4MS01OWRkMTE4ZC0xN2I4LTRlNDAtOTJkMC1hN2IzNjI3NDYxMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTZUMTMwMjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDMxMzQzZWRjZTI3NWRmNjgwNWM2NWVmYzFjNzI3MTRmOGRhNTAwM2YzMGNmZTRhMDUwZDgxOWRmYjg3OWFlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pfKECYCWV4hAvz2XtsfdZgSrbr0NfDBzIbkAqYnBUDk)
> 
> > > **BTW**:  Switching to 8.3.0 does not fix the issue. I still have this,
> 
> > > with NextJS projects...
> 
> > 
> 
> > try to edit eslint config
> 
> > 
> 
> > { "extends": "next" }
> 
> 
> 
> We are all senior Devs here, so I have done this and much more to 
> 
> solve this issue...

That sounds great. How did you solve this problem?

Under normal circumstances, you should definitely not choose to modify eslint config. This is just for me to use it temporarily. I want to wait for the official repair, but I heard that you have solved this problem, so I would like to ask for advice.

**Comment by gabrielscaranello** [comment]
Neovim released stable version [0.10.0](https://github.com/neovim/neovim/releases/tag/v0.10.0) a few minutes ago.
The issue was fixed after upgrading to the latest version of neovim.

![image](https://github.com/AstroNvim/astrocommunity/assets/44346715/170b3502-30aa-4e90-92a4-6da9359c0e26)

![image](https://github.com/AstroNvim/astrocommunity/assets/44346715/6a78b274-c914-41de-80ef-fa55ba1921b5)

I'm running on Zorin OS 17.1, and I'm manually building neovim.

**Comment by taotao7** [comment]
> Neovim released stable version [0.10.0](https://github.com/neovim/neovim/releases/tag/v0.10.0) a few minutes ago.
> 
> The issue was fixed after upgrading to the latest version of neovim.
> 
> 
> 
> ![image](https://github.com/AstroNvim/astrocommunity/assets/44346715/170b3502-30aa-4e90-92a4-6da9359c0e26)
> 
> 
> 
> ![image](https://github.com/AstroNvim/astrocommunity/assets/44346715/6a78b274-c914-41de-80ef-fa55ba1921b5)
> 
> 
> 
> I'm running on Zorin OS 17.1, and I'm manually building neovim.
> 
> 

nice 
btw：

I'm already 0.10.0, but I'm from homebrew install neovim —head. I'll try to reinstall it tomorrow.

**Comment by Uzaaft** [comment]
Wait, @taotao7  Do you use neovim nightly?

**Comment by taotao7** [comment]
> Wait, @taotao7 Do you use neovim nightly?

I have changed the official version of neovim I am using to 0.10.0, but it is still the same

**Comment by taotao7** [comment]
I retested it again, deleted astronvim and reinstalled it, after installing it was all the default configuration, and then only enabled typescript pack, still this problem, I used neovim 0.10.0 official version released yesterday

**Comment by gabrielscaranello** [comment]
> I retested it again, deleted astronvim and reinstalled it, after installing it was all the default configuration, and then only enabled typescript pack, still this problem, I used neovim 0.10.0 official version released yesterday

@taotao7, try using my configuration, just for testing purposes.  Note that there are many other settings besides TS.
[Neovim config](https://github.com/gabrielscaranello/dotfiles/blob/main/config%2Fnvim%2FREADME.md)

**Comment by taotao7** [comment]
> > I retested it again, deleted astronvim and reinstalled it, after installing it was all the default configuration, and then only enabled typescript pack, still this problem, I used neovim 0.10.0 official version released yesterday
> 
> @taotao7, try using my configuration, just for testing purposes. Note that there are many other settings besides TS. [Neovim config](https://github.com/gabrielscaranello/dotfiles/blob/main/config%2Fnvim%2FREADME.md)

Thanks I'll try it

**Comment by taotao7** [comment]
> > I retested it again, deleted astronvim and reinstalled it, after installing it was all the default configuration, and then only enabled typescript pack, still this problem, I used neovim 0.10.0 official version released yesterday
> 
> @taotao7, try using my configuration, just for testing purposes. Note that there are many other settings besides TS. [Neovim config](https://github.com/gabrielscaranello/dotfiles/blob/main/config%2Fnvim%2FREADME.md)

Yes, your configuration works for me.

**Comment by taotao7** [comment]
@gabrielscaranello  

thanks bro

I made modifications based on your configuration. I have a question. I don’t see how you configured it. When typing: Telecope can pop up.

**Comment by gabrielscaranello** [comment]
@taotao7, great that it worked for you, bro. 
The only change I made to the telescope config was to add file_ignore_patterns. Here everything works perfectly. Or maybe I didn't understand your question.

**Comment by Uzaaft** [comment]
I just tested with base v4 and typescript pack, no issues with eslint and prettier here

**Comment by taotao7** [comment]
> I just tested with base v4 and typescript pack, no issues with eslint and prettier here
Is there anything wrong with the default configuration? 
No way, we're all running into this issue, I've now respecified the format by specifying the none-ls configuration

**Comment by taotao7** [comment]
> @taotao7, great that it worked for you, bro. The only change I made to the telescope config was to add `file_ignore_patterns`. Here everything works perfectly. Or maybe I didn't understand your question.


thanks again，I mean, when using your configuration, when you enter a colon in normal mode, a telescope cmdline box pops up, and it feels like a good experience, I want to ask how you did it

**Comment by taotao7** [comment]
> I just tested with base v4 and typescript pack, no issues with eslint and prettier here

First of all, thank you, maybe you can try to open a nextjs project, configure eslint, then open the two ts files of the project, and then format the file to save one file, and modify the second file, at this time the save format will be wrong

**Comment by gabrielscaranello** [comment]
> > @taotao7, great that it worked for you, bro. The only change I made to the telescope config was to add `file_ignore_patterns`. Here everything works perfectly. Or maybe I didn't understand your question.
> 
> thanks again，I mean, when using your configuration, when you enter a colon in normal mode, a telescope cmdline box pops up, and it feels like a good experience, I want to ask how you did it

The plugin that does this is [noice.nvim](https://github.com/folke/noice.nvim). It's not a telescope dialog (although it looks like it), it's a prompt for command mode in neovim.

**Comment by Uzaaft** [comment]
> > I just tested with base v4 and typescript pack, no issues with eslint and prettier here
> 
> First of all, thank you, maybe you can try to open a nextjs project, configure eslint, then open the two ts files of the project, and then format the file to save one file, and modify the second file, at this time the save format will be wrong

Already done. Works fine for me.

**Comment by taotao7** [comment]
> > > I just tested with base v4 and typescript pack, no issues with eslint and prettier here
> 
> > 
> 
> > First of all, thank you, maybe you can try to open a nextjs project, configure eslint, then open the two ts files of the project, and then format the file to save one file, and modify the second file, at this time the save format will be wrong
> 
> 
> 
> Already done. Works fine for me. 

Close it. I'm fine now after reconfiguring it according to my brother upstairs.

**Comment by luxus** [comment]
i wish i have a brother upstairs!
