### ISSUE TITLE
Formatting is broken

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#974]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

For a couple of days, the formatting with Javascript is broken.
 I think it is an issue with prettier and/or eslint. Everything 
is working with VS Code and Helix... 
I saw few days ago that prettier was updated/upgraded and this 
broke the formatting. Everything was OK before.

![Capture d’écran du 2024-05-18 13-08-05](https://github.com/AstroNvim/astrocommunity/assets/5823264/b87d3f67-10af-47ca-ab83-3dbe27f8ec58)

### Steps to Reproduce

When I save a file, formatting failed

### Expected behavior

formatting

### Screenshots

see above

**Comment by Uzaaft** [comment]
Do you have any custom logic locally?

**Comment by Uzaaft** [comment]
This has been raised earlier @MrMic. Not sure what's causing this, but I can't reproduce locally. All LSP's are up to date. Basic template +  typescript pack.

**Comment by Uzaaft** [comment]
What do you mean with "broken" @MrMic. Broken as in non-functional, or broken as in wrong formatting?

**Comment by MrMic** [comment]
No custom logic.
LSP is OK.
The issue is with formatting, which does not work at all with JS / TS.
All was working fine around 10 or 15 days ago. And then, I saw an update/upgrade 
and the formatting went wrong. And now, it is not working at all!

**Comment by MrMic** [comment]
Moreover when I install prettier in my project Dev Dependencies:
`
$> npm install --save-dev --save-exact prettier
`
and run:
`
$> npx prettier . --write
`
Everything works as expected... I mean formatted.

**Comment by Skarian** [comment]
This is a significant issue. I am having the same problem, formatting completely broken in JS/TS.

**Comment by Uzaaft** [comment]
I Wonder if this is due to prettierd

**Comment by MrMic** [comment]
I think so. 
This bug happens when prettier was updated/upgraded a couple of days ago.

**Comment by Uzaaft** [comment]
I'll take a look and try and debug this, but no promises on a timeline. Feel free to also investigate the issue and come up with a fix. I'm very pressed on times nowadays @Skarian  @MrMic

**Comment by vadimshvetsov** [comment]
Today I've updated AstroNvim and formatting was completely broken for all my TS projects.
I have some easy repro steps:
- Start new app with `create-next-app` with TailwindCSS (didn't test without)
- Create new AstroNvim config and add community packages:
```
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.typescript" },
}
```
- Go to `src/app/page.tsx` file and save - everything will be fine
- Go to the next file `src/app/layout.tsx` and save - everything will be shifted to the line start.

So the first file save is always ok, but the second is always shifting all the contents to the start of line.
![image](https://github.com/AstroNvim/astrocommunity/assets/16336572/6a947b90-e307-4187-857b-a3fe5de15d36)

**Comment by MrMic** [comment]
> Today I've updated AstroNvim and formatting was completely broken for all my TS projects. I have some easy repro steps:
> 
> * Start new app with `create-next-app` with TailwindCSS (didn't test without)
> * Create new AstroNvim config and add community packages:
> 
> ```
> return {
>   "AstroNvim/astrocommunity",
>   { import = "astrocommunity.pack.tailwindcss" },
>   { import = "astrocommunity.pack.typescript" },
> }
> ```
> 
> * Go to `src/app/page.tsx` file and save - everything will be fine
> * Go to the next file `src/app/layout.tsx` and save - everything will be shifted to the line start.
> 
> So the first file save is always ok, but the second is always shifting all the contents to the start of line. ![image](https://private-user-images.githubusercontent.com/16336572/332964134-6a947b90-e307-4187-857b-a3fe5de15d36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTQzMzksIm5iZiI6MTcxNjQxNDAzOSwicGF0aCI6Ii8xNjMzNjU3Mi8zMzI5NjQxMzQtNmE5NDdiOTAtZTMwNy00MTg3LTg1N2ItYTNmZTVkZTE1ZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIxNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5M2NjOTQ4MGExYWU2M2Y3MjUxMDJmNmZjOTQzYzNhYzY3OTRjMjc0ZTlhNDkwOTFmOTRkMWZkMzU0ZTRjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Bjqg-T4o9z6nqV28xgzWNTXWAyM7JEpl--r73drR-Q)

Got the same issue!

**Comment by Uzaaft** [comment]
@vadimshvetsov  Feel free to help us in fixing this.

**Comment by vadimshvetsov** [comment]
I removed the Tailwind CSS pack and reproduced the issue, so it looks like the problem is somewhere in the TypeScript pack.

**Comment by Uzaaft** [comment]
We've already established that.

**Comment by Uzaaft** [comment]
I checked the two latest commits to the typescript pack, and those didn't break anything

**Comment by MrMic** [comment]
I  saw the update of prettier a couple of days ago (10 or 15 days) and it was
for the core of Astronvim not with the community packages. If I remember well.
And from this point on I got issues with formatting.

**Comment by vadimshvetsov** [comment]
I've rollbacked to my previous lock file and updated just astrocommunity to 8.5 and can't see any issue with formatting. I'll update packages one by one and will find which one causes the issue.

**Comment by vadimshvetsov** [comment]
To whom who are blocked by this issue - you can change version in `lazy-lock.json`:
```json
  "AstroNvim": { "branch": "main", "commit": "0f875f4a7f1963d6c61eb564cadb8e556e406dd5" },
```
And after opening nvim just run `:Lazy restore`, it will pickup the last working formatting version.

Right after this commit I have this issue (came in AstroNvim 4.5.1):
https://github.com/AstroNvim/AstroNvim/commit/f3dbb860e76b5a2de2a301fc7b7ad1cc3b590150

**Comment by Uzaaft** [comment]
Wait. That shouldn't, if I'm thinking correctly, affect the prettier stuff

**Comment by Uzaaft** [comment]
Prettier should override that anyways since it has its own prefered logic for tabs/spaces.

**Comment by vadimshvetsov** [comment]
I've updated all my packages back to the latest and just put `:set shiftwidth=2` - its working perfectly now for me 🤷‍♂️

Checked with latest `create-next-app` also.

**Comment by vadimshvetsov** [comment]
I guess prettier ignores `tabWidth` setting somehow.

**Comment by Uzaaft** [comment]
I think this just exposes an underlying issue with the prettier/prettierd and neovim.

**Comment by Uzaaft** [comment]
Issue is upstream:
https://github.com/pmizio/typescript-tools.nvim/pull/270

**Comment by MrMic** [comment]
I notice an update but I still have no formatting and null-ls seems to get stuck at 
the bottom right corner of the UI.

![Capture d’écran du 2024-05-23 14-14-16](https://github.com/AstroNvim/astrocommunity/assets/5823264/ceae880a-3dd1-4e00-aad9-8821beac5e12)

**Comment by Uzaaft** [comment]
It hasn't been merged yet...

**Comment by Uzaaft** [comment]
Issue is resolved for me with a basic template + typescript pack. nothing else init.

**Comment by Uzaaft** [comment]
I think this issue is proof that we should move away from typescript-tools.nvim to vtsls lsp instead.

**Comment by mehalter** [comment]
This should be fixed now that we have moved to `vtsls`. Let me know if this should be reopened.

**Comment by MrMic** [comment]
Not OK for me! 
Sorry. 
null-ls seems to be stuck with prettierd

![Capture d’écran du 2024-05-24 14-12-52](https://github.com/AstroNvim/astrocommunity/assets/5823264/35b85a77-07c2-4073-b023-9709a5026ceb)

![Capture d’écran du 2024-05-24 14-12-23](https://github.com/AstroNvim/astrocommunity/assets/5823264/00065b32-c5c8-4b90-b9b6-ac2b1ef958ad)

**Comment by Uzaaft** [comment]
Make sure to update your dependencies @MrMic . It's working fine for me now

**Comment by mehalter** [comment]
Also open Mason and make sure to uninstall tsserver

**Comment by MrMic** [comment]
> Also open Mason and make sure to uninstall tsserver

I did it again. And it has been installed again but I still have the same issue...
tsserver works perfectly fine, it is an issue with prettier(d) and formatting.
One or 2 weeks ago I saw updates for prettier and since then I got issues.

**Comment by mehalter** [comment]
Well you shouldn't see tsserver at all in the latest update 😅 so it shouldn't be working at all haha . Can you share an example project that's throwing the error and steps to replicate.

**Comment by MrMic** [comment]
I see it when I open my project...
Anyway, here it is:
https://github.com/MrMic/NextJS-14-S04_NEW.git

BTW: When I work with VS Code on it I have no issue at all!

**Comment by mehalter** [comment]
It would definitely be strange if you got a null-ls error message in vs code 😂

**Comment by Uzaaft** [comment]
@MrMic  delete your plugins and try again.

**Comment by Uzaaft** [comment]
I.e the lazy cache folder

**Comment by MrMic** [comment]
> I.e the lazy cache folder

Where is it located? (on linux)

**Comment by Uzaaft** [comment]
I've send you it before 😐 
```bash
rm -rf ~/.cache/nvim
rm -rf ~/.local/share/nvim
rm -rf ~/.local/state/nvim
```
Also: List time you had a bug in a plugin, you  "...deleted and reinstalled the plugin, and this solved my issue... weird." Whatever that meant, try that as well.

**Comment by mehalter** [comment]
@MrMic I don't have any issues formatting that project, also it correctly only attaches `vtsls` and `eslint`, it doesn't add `prettier` at all. Can you share your config? You might have a bug on your end

**Comment by MrMic** [comment]
> I've send you it before 😐
> 
> ```shell
> rm -rf ~/.cache/nvim
> rm -rf ~/.local/share/nvim
> rm -rf ~/.local/state/nvim
> ```
> 
> Also: List time you had a bug in a plugin, you "...deleted and reinstalled the plugin, and this solved my issue... weird." Whatever that meant, try that as well.

Done. But I still have this issue...

**Comment by MrMic** [comment]
> @MrMic I don't have any issues formatting that project, also it correctly only attaches `vtsls` and `eslint`, it doesn't add `prettier` at all. Can you share your config? You might have a bug on your end

https://github.com/MrMic/astronvim_v4.git

**Comment by mehalter** [comment]
I get a 404, that might be private

**Comment by MrMic** [comment]
> I get a 404, that might be private

Yes indeed. Should be public now for some time...

**Comment by mehalter** [comment]
Ok, I found the error. Investigating now.

**Comment by Uzaaft** [comment]
> Ok, I found the error. Investigating now.

Seems to be a reccuring thing with your config @MrMic 😂

**Comment by mehalter** [comment]
Ok @MrMic , AstroNvim v4.7.7 should resolve the specific error message you are getting, but there are still a lot of issues with your configuration. I will make a PR with a few fixes I found immediately, but I haven't really gone through it with a fine tooth comb

**Comment by mehalter** [comment]
Ok, I opened a PR on your config. Hopefully it all makes sense. God speed!

https://github.com/MrMic/astronvim_v4/pull/1
